### ISSUE TITLE
pirateship hotspot errors when password shorter then 8

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#77]
```
pirateship hotspot housetrees tree
/usr/lib/node_modules/@pirateship/cli/lib/ConfigureHotspot.js:58
    if (password.length < 8 ) throw new Error("Password must be over 8 characters long!");
                              ^

Error: Password must be over 8 characters long!
    at Command.module.exports (/usr/lib/node_modules/@pirateship/cli/lib/ConfigureHotspot.js:58:37)
    at Command.listener (/usr/lib/node_modules/@pirateship/cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/usr/lib/node_modules/@pirateship/cli/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/lib/node_modules/@pirateship/cli/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/usr/lib/node_modules/@pirateship/cli/cli.js:90:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

**Comment by i5o** [comment]
easy fix:
https://github.com/ole-vi/pirateship/blob/master/lib/hotspot.js#L58
Replace it for
```
console.log("Password must be over 8 characters long!");
return
```

**Comment by i5o** [comment]
https://github.com/ole-vi/pirateship/commit/23935c091c7fb3d0330e6ad80bd08db8cc50b6a1
