### ISSUE TITLE
raspbian stretch is out

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#97]

**Comment by i5o** [comment]
- [ ] default
- [ ] rename <hostname>
- [ ] wifi <ESSID> [password]
- [ ] staticwifi <ip> <mask> <gateway> <dns> 
- [ ] ethernet <ip> <mask> <gateway> <dns>
- [ ] hotspot <ESSID> [password]  
- [ ] expandfs
- [ ] detectrpi 
- [ ] version 
- [ ] docker 
- [ ] password <password>

**Comment by i5o** [comment]
```
root@raspberrypi:/home/pi# pirateship rename ignaciopi
/usr/lib/node_modules/@pirateship/cli/lib/ReconfigureHostname.js:34
            if (error) return callback(error)
                              ^

TypeError: callback is not a function
    at /usr/lib/node_modules/@pirateship/cli/lib/ReconfigureHostname.js:34:31
    at ChildProcess.exithandler (child_process.js:278:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
root@raspberrypi:/home/pi#
```

**Comment by i5o** [comment]
Testing in rpi2

```
root@raspberrypi:/home/pi# pirateship hotspot Ignaxio 12345678
This pirateship has anchored successfully!
exec error: Error: Command failed: ifdown uap0
ifdown: unknown interface uap0

exec error: Error: Command failed: ifup uap0
ifup: unknown interface uap0

root@raspberrypi:/home/pi#
```

**Comment by i5o** [comment]
pirateship hostname

Funny thing, the hostname is there even after the commadn failed

**Comment by i5o** [comment]
**--- retesting in raspberry pi 3 ---**

**Comment by i5o** [comment]
pirateship
- [ ] default
- [ ] rename <hostname>
- [ ] wifi <ESSID> [password]
- [ ] staticwifi <ip> <mask> <gateway> <dns> 
- [ ] ethernet <ip> <mask> <gateway> <dns>
- [ ] hotspot <ESSID> [password]  
- [ ] expandfs
- [ ] detectrpi 
- [ ] version 
- [ ] docker 
- [ ] password <password>

**Comment by i5o** [comment]
```
root@raspberrypi:/home/pi# pirateship rename ignaciopi
/usr/lib/node_modules/@pirateship/cli/lib/ReconfigureHostname.js:34
            if (error) return callback(error)
                              ^

TypeError: callback is not a function
    at /usr/lib/node_modules/@pirateship/cli/lib/ReconfigureHostname.js:34:31
    at ChildProcess.exithandler (child_process.js:278:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
root@raspberrypi:/home/pi# hostname
raspberrypi
root@raspberrypi:/home/pi# exit
```

**Comment by i5o** [comment]
**Action: will fix hostname and continue**

**Comment by i5o** [comment]
```
root@ignaciopi:/home/pi# pirateship password ignacio
password change success
root@ignaciopi:/home/pi#
```
